parameters:
    openrouter.api_key: '%env(OPENROUTER_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $apiKey: '%env(OPENROUTER_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
